### ISSUE TITLE
how to select multiple or all hosts at once? and how to stop refreshing?

### ISSUE THREAD

**Issue by mountaincastle47** [hmz777/NetStalker#18]
any option for it?

**Comment by hmz777** [comment]
The select all hosts functionality will be added, but what's the point of stopping the auto refresh?

**Comment by mountaincastle47** [comment]
because when i try to block one host it just shifts away because it detected a new host, making me to block not the intended host

**Comment by hmz777** [comment]
What do you mean by "shifts away"?
