### ISSUE TITLE
Add option to disable "background scanning"

### ISSUE THREAD

**Issue by baka24** [hmz777/NetStalker#2]
Is it possible to add an option to disable **background scanning**?
Because **NetStalker** uses 10-12% CPU Usage (in my phenom x4 955) at idle

Thank You.

**Comment by hmz777** [comment]
@baka24 I am planning on a complete rewrite of this project with a cleaner codebase and updated dependencies... etc. as soon as i am finished with my current one which will be in a couple of weeks.
I did some tests on cpu usage when i made this software and even on my old laptop which has an Intel Core i3 1st gen, it didn't go above 5% on idle.
Anyway i will take your suggestion into consideration.
