### ISSUE TITLE
Devices Getting Blocked on redirection check 

### ISSUE THREAD

**Issue by waelfawal** [hmz777/NetStalker#20]
I tried to speed limit devices but when I check redirect they got blocked automatically and I cannot uncheck block toggle

**Comment by hmz777** [comment]
It's just a UI procedure, I disable the blocking checkbox and check it during redirection since I do not allow to check both manually.
You can just redirect a device and try to use it, it'll still have internet access.

**Comment by waelfawal** [comment]
Oh ok, i think if you made it disabled it will be more clear 
and nice work
