### ISSUE TITLE
Add limit all devices option please

### ISSUE THREAD

**Issue by mountaincastle47** [hmz777/NetStalker#22]
It's a pain in the ass to limit each device individually so that option would be great

**Comment by hmz777** [comment]
I am considering a bigger feature that includes this one, but it won't be released so soon because I am busy with other stuff. I'll update this issue when there is progress.

**Comment by MrSniFo** [comment]
any updates...

**Comment by hmz777** [comment]
@MrSniFo Yes! There is a new version, rebuilt from scratch with a more advanced targeting method.
