### ISSUE TITLE
Tagged Malicious in VirusTotal

### ISSUE THREAD

**Issue by Skyhawk1207** [hmz777/NetStalker#31]
The installer is showing  as malware by 5 vendors in VirusTotal.

Screenshot-
![image](https://github.com/hmz777/NetStalker/assets/68462875/9928eb9f-fba7-4113-831f-afa8354ab726)

Link - https://www.virustotal.com/gui/file/76bd3c9047a2953fb09e1328922c46053049080fe6c366857fffd13c888b4ccd

**Comment by hmz777** [comment]
The packaging of this version is done using [Advanced Installer](https://www.advancedinstaller.com/). If you're paranoid, you can just build it from the source.

The [new version](https://github.com/hmz777/NetStalker.Avalonia) is packaged using Inno Setup which is also open source, so you could use the new version instead.
