### ISSUE TITLE
Can I get HTTP data in Linux?

### ISSUE THREAD

**Issue by bbhxwl** [hmz777/NetStalker#7]
Can I get HTTP data in Linux?

**Comment by hmz777** [comment]
I don't understand what you want exactly. Could you explain more please?

**Comment by bbhxwl** [comment]
> I don't understand what you want exactly. Could you explain more please?

I want to get the number of visits and visitors IP of all my own websites on the server. Do a Linux server monitoring.

**Comment by hmz777** [comment]
This is a traffic shaping tool that works over the local network only!
Please take sometime to read the project description before opening an issue,
